services:
  - type: web
    name: daten-ai-backend
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: BACKEND_HOST
        value: 0.0.0.0
      - key: CORS_ORIGINS
        value: "*"
      - key: MAX_FILE_SIZE_MB
        value: 50
      - key: EXECUTION_TIMEOUT_SECONDS
        value: 300